apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  namespace: client-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: pern-client-container-k8s
          image: amanappperfect/pern_client_image:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: client-service
  namespace: client-ns
spec:
  selector:
    app: react-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
