version: "3.8"
services:
server:
  container_name: pern-server-container
  image: pern-server-image:latest
  depends_on:
    - db
  ports:
    - 5000:5000
  networks:
    - app-network

postgres-db:
  image: postgres:16
  restart: always
  environment:
    - POSTGRES_USER=appperfect
    - POSTGRES_PASSWORD=postgres
  ports:
    - "5432:5432"
  volumes:
    - database:/var/lib/postgresql/data
    - ./server/data/movie.sql:/docker-entrypoint-initdb.d/movie.sql

client:
  container_name: pern-client-container
  image: pern-client-image:latest
  depends_on:
    - server
  ports:
    - "3000:3000"
  networks:
    - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-db:
    driver: local
