version: '1.0'
services:
  db:
    container_name: node_docker_postgres_container
    image: postgres
    ports:
      - 5432:5432/tcp
    environment:
      POSTGRES_DB: filmdb
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - pgData:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  server:
    build:
      context: server
      dockerfile: Dockerfile
    image: node_docker_server_image
    container_name: node_docker_server_container
    command: npm start
    ports:
      - 5000:5000/tcp
    depends_on:
      - db
  client:
    build:
      context: client
      dockerfile: Dockerfile
    image: node_docker_client_image
    container_name: node_docker_client_container
    command: npm start
    ports:
      - 3000:3000/tcp
    depends_on:
      - server
volumes:
  pgData:
