apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: pern-server-container-k8s
        image: amanappperfect/pern_server_image:latest 
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata: 
  name: server-service
spec:
  selector: 
    app: node-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000