version: '3'

tasks:
  list-all-res:
    cmds:
      - kubectl get all -A
      - kubectl get pvc -A
      - kubectl get pv -A
      - kubectl get configmap -A
      - kubectl get secret -A

  get-res:postgres:
    cmds:
      - kubectl get all -n postgres-ns
      - kubectl get pvc -n postgres-ns
      - kubectl get pv -n postgres-ns
      - kubectl get configmap -n postgres-ns
      - kubectl get secret -n postgres-ns

  deploy:client:
    cmds:
      - kubectl create namespace client-ns
      - kubectl apply -f client.yaml
      - kubectl get all -n client-ns

  deploy:server:
    cmds:
      - kubectl create namespace server-ns
      - kubectl apply -f server.yaml
      - kubectl get all -n server-ns

  deploy:postgres:
    cmds:
      - kubectl create namespace postgres-ns
      - kubectl apply -f postgres-secret.yaml
      - kubectl create configmap db-init-script --from-file=init.sql -n postgres-ns
      - kubectl apply -f psql-pv.yaml
      - kubectl apply -f psql-claim.yaml
      - kubectl apply -f postgres.yaml
      - task: get-res:postgres
  
  build-and-push:client:
    cmds:
      - cd client && docker build -t amanappperfect/pern_client_image:latest .
      - docker push amanappperfect/pern_client_image:latest
  
  build-and-push:server:
    cmds:
      - cd server && docker build -t amanappperfect/pern_server_image:latest .
      - docker push amanappperfect/pern_server_image:latest

  destroy:cluster:
    cmds:
      - kubectl delete namespace client-ns
      - kubectl get all -n client-ns
      - kubectl delete namespace server-ns
      - kubectl get all -n server-ns
      - kubectl delete namespace postgres-ns
      - task: get-res:postgres